sudo: "required"
dist: "trusty"
language: "node_js"
env:
  global:
    - secure: "STxhfQh/AHeyRJgErinjZrjnJDChHKLctjqAUDwiIWcZZonopfB8DNp6DgcCHj6FPCTfcHeWdjQjvOiC6ZZugMcMUwzhi+PdDR4kDVP3GoeaMcKC2ckkdjapcA+mnmJDLF35FjhK6PvR1zpRbwlwiYpIayKHEjdgEzna3RmfRH8="
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_install:
  - "npm -g install npm@latest"
  - "gem install travis"
before_script:
  - "npm run lint"
script:
  - "npm test"
  - "npm run test:hooks-handlers"
after_success:
  - "npm run coveralls"
deploy:
  provider: "npm"
  skip_cleanup: true
  email: "sre@apiary.io"
  api_key:
    secure: "b8eq7IWr2cDPR6+wHAgfnXzJ41KePcNVk83oKCroRwqRsgJalkV5WFh/btz8lP2u0Vf806LbQAAlPEmN4mAKkbn1PsTakSZxdtzID3mTipdnnisOi1r0pa479OybrzW/ttTs8WSOw6eEY690hSErfGqyUNlB1H4nvAu4bmn9lsk="
  on:
    repo: "apiaryio/dredd"
    branch: "master"
    node: "6"
